language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - windows
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

script:
  - cargo build
  - cargo test
  - cargo test --release
