[package]
name = "repository"
version = "0.1.0"
authors = ["Vincent Rouillé <vincent@speedy37.fr>"]

[dependencies]
brotli = "3.3"
clap = "2.32"
env_logger = "0.6"
futures = "0.1"
futures-cpupool = "0.1"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
sha1 = "0.3"
updater = { path = "../../updater" }
